"""Generate CLAUDE.md for the project workspace."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

from forge_cli.config_schema import ForgeConfig


def generate_claude_md(config: ForgeConfig, project_dir: Path) -> None:
    """Generate CLAUDE.md in the project root."""
    agents = config.get_active_agents()
    non_leader_agents = [a for a in agents if a != "team-leader"]

    tech_parts = []
    if config.tech_stack.languages:
        tech_parts.append(", ".join(config.tech_stack.languages))
    if config.tech_stack.frameworks:
        tech_parts.append(", ".join(config.tech_stack.frameworks))
    tech_str = " | ".join(tech_parts) if tech_parts else "(auto-detect)"

    agent_roster = "\n".join(
        f"- **{a}**: `.claude/agents/{a}.md`" for a in non_leader_agents
    )

    atlassian_section = ""
    if config.atlassian.enabled:
        atlassian_section = dedent(f"""\

        ## Atlassian Integration

        Jira and Confluence are configured via `.claude/mcp.json`. All agents have access.
        - **Jira**: {config.atlassian.jira_base_url or '[see mcp.json]'} — Project: {config.atlassian.jira_project_key or '[see mcp.json]'}
        - **Confluence**: {config.atlassian.confluence_base_url or '[see mcp.json]'} — Space: {config.atlassian.confluence_space_key or '[see mcp.json]'}

        The Scrum Master agent manages the Jira board, sprint planning, and Confluence documentation.
        All agents must update ticket status and add comments as they work.
        Documentation is a side effect of development — make reasoning visible in Confluence.
        """)

    spawning_section = ""
    if config.agents.allow_sub_agent_spawning:
        spawning_section = dedent("""\

        ## Sub-Agent Spawning

        Agents are authorized to spawn sub-agents for parallel task execution.
        - All sub-agents MUST use instruction files from `.claude/agents/`
        - Sub-agents report to their spawning agent, not directly to Team Leader
        - Cross-specialty spawning is allowed (e.g., backend agent spawns frontend sub-agent to check impacts)
        - Maximum spawning depth: 2-3 levels
        """)

    naming_section = ""
    if config.agent_naming.enabled:
        naming_section = dedent(f"""\

        ## Agent Naming

        Each agent assigns itself a unique name upon initialization ({config.agent_naming.style} style).
        Agent names are used in: git commits, branch names, Jira updates, Confluence edits, and all communications.
        This enables traceability — humans can see exactly which agent did what.
        """)

    content = dedent(f"""\
    # Forge — Team Leader Context

    > Auto-generated by Forge. Regenerate with: `forge generate --config forge-config.yaml`

    ## Project Configuration

    - **Project**: {config.project.description}
    - **Mode**: {config.mode.value} | **Strategy**: {config.strategy.value}
    - **Cost Cap**: ${config.cost.max_development_cost}
    - **Team Profile**: {config.resolve_team_profile()} ({', '.join(agents)})
    - **Tech Stack**: {tech_str}

    ## Your Identity

    You are the **Team Leader** of a Forge agent team. You ARE this interactive
    Claude Code session. The user talks directly to you.

    When the user asks a question, answer directly. When they give a directive, act on it.

    **CRITICAL: Command Priority**
    User commands take ABSOLUTE priority. When the user types anything, respond
    immediately. Agent work continues in the background.

    ## Getting Started

    Read `team-init-plan.md` for the complete initialization blueprint. It contains:
    1. The startup sequence
    2. Iteration 1 task decomposition
    3. Agent spawning instructions
    4. Quality gates and success criteria

    ## Agent Roster

    Available agents (spawn via Agent tool with instruction files as context):
    {agent_roster}

    ## Spawning an Agent

    To spawn an agent, use the **Agent tool** with:
    - The agent's instruction file from `.claude/agents/{{agent-type}}.md` as system context
    - A clear task description
    - Any relevant context (API contracts, design specs, etc.)

    Example: To spawn the backend developer, use the Agent tool and include the
    contents of `.claude/agents/backend-developer.md` in the system prompt.
    {atlassian_section}{spawning_section}{naming_section}
    ## Visual Verification

    Playwright MCP is configured in `.claude/mcp.json` for browser automation and screenshots.
    - Frontend agents and QA must **visually verify** their work via screenshots before marking tasks complete
    - Use Playwright CLI or MCP to capture screenshots, then use the Read tool to view them
    - Screenshots are saved to `docs/screenshots/` for human review
    - Smoke tests must include screenshot evidence of a working UI

    ## Project Requirements

    {config.project.requirements or config.project.description}

    ## Team Leader Instructions

    Your full instruction set is in `.claude/agents/team-leader.md`. Key responsibilities:
    - 7-phase iteration lifecycle (PLAN → EXECUTE → TEST → INTEGRATE → REVIEW → CRITIQUE → DECISION)
    - Quality gates: {'70%' if config.mode.value == 'mvp' else '90%' if config.mode.value == 'production-ready' else '100%'}
    - Smoke test protocol (mandatory for ALL modes)
    - Progressive work advancement (don't wait for all agents to finish)
    - Parallel work streams with sync points
    """)

    output_path = project_dir / "CLAUDE.md"
    output_path.write_text(content)
