#!/usr/bin/env bats
# ==============================================================================
# Integration: Agent file generation with real yq
# ==============================================================================
load '../test_helper/common'

setup() {
    create_test_environment
    export MOCK_YQ_PASSTHROUGH="true"
    create_test_config "mvp" "auto-pilot" "agent-teams"
}

teardown() {
    destroy_test_environment
}

@test "agent files: generated files have auto-generated header" {
    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local gen_file="$PROJECT_DIR/.forge/agents/backend-developer.md"
    [ -f "$gen_file" ]

    run head -3 "$gen_file"
    [[ "$output" == *"Generated by init-project.sh"* ]]
    [[ "$output" == *"DO NOT EDIT MANUALLY"* ]]
}

@test "agent files: contain Project Context section" {
    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local gen_file="$PROJECT_DIR/.forge/agents/architect.md"
    run cat "$gen_file"
    [[ "$output" == *"## Project Context"* ]]
}

@test "agent files: contain mode/strategy/profile" {
    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local gen_file="$PROJECT_DIR/.forge/agents/qa-engineer.md"
    run cat "$gen_file"
    [[ "$output" == *"**Mode**: mvp"* ]]
    [[ "$output" == *"**Strategy**: auto-pilot"* ]]
    [[ "$output" == *"**Team Profile**: lean"* ]]
}

@test "agent files: contain requirements" {
    # Add test requirements
    echo "Build a REST API with user auth" > "$FORGE_DIR/config/project-requirements.md"

    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local gen_file="$PROJECT_DIR/.forge/agents/backend-developer.md"
    run cat "$gen_file"
    [[ "$output" == *"Build a REST API with user auth"* ]]
}

@test "agent files: end with original template content" {
    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local gen_file="$PROJECT_DIR/.forge/agents/team-leader.md"
    local template_file="$FORGE_DIR/agents/team-leader.md"

    # The last line of the generated file should match content from the template
    # Check that the template's first heading appears in the generated file
    local template_heading
    template_heading=$(grep "^#" "$template_file" | head -1)
    run cat "$gen_file"
    [[ "$output" == *"$template_heading"* ]]
}

@test "agent files: full profile generates more agents than lean" {
    create_test_config "production-ready" "auto-pilot" "agent-teams"

    run bash "$FORGE_DIR/scripts/init-project.sh" \
        --config "$FORGE_DIR/config/team-config.yaml" \
        --project-dir "$PROJECT_DIR"
    [ "$status" -eq 0 ]

    local full_count
    full_count=$(ls -1 "$PROJECT_DIR/.forge/agents/"*.md | wc -l)

    # Full profile should have >8 agents (lean has 8)
    [ "$full_count" -gt 8 ]
}
